version: '3.8'
services:
  hadoop-base:
    build:
      context: ./hadoop-base
    image: hadoop-base

  namenode:
    build:
      context: ./namenode
    image: namenode
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode:/hadoop/dfs/name
    depends_on:
      - hadoop-base

  datanode:
    build:
      context: ./datanode
    image: datanode
    container_name: datanode
    ports:
      - "9864:9864"
    volumes:
      - datanode:/hadoop/dfs/data
    depends_on:
      - namenode

  resourcemanager:
    build:
      context: ./resourcemanager
    image: resourcemanager
    container_name: resourcemanager
    ports:
      - "8088:8088"
    depends_on:
      - namenode

  nodemanager:
    build:
      context: ./nodemanager
    image: nodemanager
    container_name: nodemanager
    ports:
      - "8042:8042"
    depends_on:
      - resourcemanager
      
  jupyter_notebook:
    build: ./jupyter_notebook
    container_name: jupyter_notebook
    volumes:
      - work:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - CLUSTER_NAME=test
    depends_on:
      - namenode
    command: "start-notebook.sh --NotebookApp.token="
    
volumes:
  namenode:
  datanode:
  work:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/nhatrinh/docker/hadoop-test/work"

